### ISSUE TITLE
bug: pnpm build is not rebuilding dist folder after being deleted

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-turbo#1053]
### Provide environment information

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 3.94 GB / 15.36 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.21 - ~/.local/share/pnpm/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.4 - ~/.local/share/pnpm/pnpm
    bun: 1.1.3 - ~/.bun/bin/bun

### Describe the bug

After deleting the either compiled `dist` folder in either `packages/db` or `packages/api`, when you call pnpm build for that directory once again, it seems that turbo is caching the result and not outputing the `dist` folder once again.

### Link to reproduction

I mean... this repo?

### To reproduce

1. `pnpm i` on a clean repo (after doing `pnpm clean:workspaces`)
2. `pnpm build -F api` or `pnpm build -F db`.
3. Delete the dist folder of either package
4. `pnpm build -F api`
5. You'll receive a >>> FULL TURBO message and you will be sad.

### Additional information

https://www.loom.com/share/87c7ac25faa242c8888217927fd11c0d?sid=2487cce1-ae7a-414e-a30b-8dcb69845db0

**Comment by juliusmarminge** [comment]
I think You have to delete the tsbuildinfo

**Comment by noxify** [comment]
Had the same behavior. Tried it with the clean command + deleting the `/.turbo` directory.
Sometimes it worked... sometimes not.

Workaround is currently to use an alternative compiler/bundler.
But not sure if this works for all use cases.

Currently I use `tsup`, but `pkgroll` or something else should work, too.

**Comment by noxify** [comment]
@dBianchii i spent some time at stackoverflow and found the following:
Found it via https://stackoverflow.com/questions/59055799/tsc-not-creating-the-dist-folder


Updated my `build` command to

```
    "build": "rimraf dist/ && rimraf node_modules/.cache/tsbuildinfo.json && tsc --noEmit false --outDir dist",
```

and it seems to work

**Comment by noxify** [comment]
Hi,

short update: I'm currently evaluating the usage of "tsx" in prod via

```
node --import tsx src/index.ts
```

The `node` command is called in the Dockerfile of my app.
With this call I don't have to call `tsc` or `tsup` can export always the ts files ( and there are no dev/build scripts inside the packages - if not needed (e.g. to generate the locale files) )

Why?
Maybe it was just a misconfiguration on my side, but with the compiled files it got some errors while running vitest.
If I fixed these issues, then the build failed... it's annoying and to make it work, I decided to switch to another approach.

Should we do it? Yes, no, maybe.

There is a gh issue where they did a quick benchmark.
https://github.com/TypeStrong/ts-node/issues/104#issuecomment-1941702624

I added "tsx" as `dependency` and everything seems to work as expected.
Have to test it in our K8S environment to see if we will get some memory/performance issues.

**Comment by juliusmarminge** [comment]
> I only managed to make it build again and output the dist folder, after deleting both `packages/api/node_modules/.cache/tsbuildinfo.json` and after deleting the root `node_modules/.cache` folder.

I don't think you have to delete the root one, just the one for the task you wanna bust the cache for. I don't know if typescript is able to restore the output or if it just uses the cache for incremental builds. Do you get a different behavior in a more minimal reproduction environment?

**Comment by dBianchii** [comment]
> > I only managed to make it build again and output the dist folder, after deleting both `packages/api/node_modules/.cache/tsbuildinfo.json` and after deleting the root `node_modules/.cache` folder.
> 
> I don't think you have to delete the root one, just the one for the task you wanna bust the cache for. I don't know if typescript is able to restore the output or if it just uses the cache for incremental builds. Do you get a different behavior in a more minimal reproduction environment?

I am using exactly stock create-t3-turbo. I just confirmed now that even after I delete only `packages/api/node_modules/.cache/tsbuildinfo.json` and run `pnpm build -F @acme/api`, FULL TURBO will still appear and no dist folder appears.

**Comment by dBianchii** [comment]
Fixed by https://github.com/t3-oss/create-t3-turbo/pull/1140!! :tada: 

Thank you @juliusmarminge
